const UserList = [
  {
    id: 1,
    name: "John Doe",
    username: "johndoe",
    age: 30,
    nationality: "US",
    friends: [
      {
        id: 2,
        name: "Alice Smith",
        username: "alicesmith",
        age: 28,
        nationality: "UK",
      },
      {
        id: 3,
        name: "Elsa Johnson",
        username: "elsaj",
        age: 25,
        nationality: "CA",
      },
      {
        id: 4,
        name: "Bob Brown",
        username: "bobbrown",
        age: 32,
        nationality: "AU",
      },
      {
        id: 5,
        name: "Sara Lee",
        username: "saralee",
        age: 27,
        nationality: "NZ",
      },
      {
        id: 6,
        name: "Mike Taylor",
        username: "miketaylor",
        age: 29,
        nationality: "US",
      },
      {
        id: 7,
        name: "Emily White",
        username: "emilyw",
        age: 26,
        nationality: "UK",
      },
    ],
  },
  {
    id: 2,
    name: "Alice Smith",
    username: "alicesmith",
    age: 28,
    nationality: "UK",
  },
  {
    id: 3,
    name: "Elsa Johnson",
    username: "elsaj",
    age: 25,
    nationality: "CA",
  },
  {
    id: 4,
    name: "Bob Brown",
    username: "bobbrown",
    age: 32,
    nationality: "AU",
  },
  {
    id: 5,
    name: "Sara Lee",
    username: "saralee",
    age: 27,
    nationality: "NZ",
  },
  {
    id: 6,
    name: "Mike Taylor",
    username: "miketaylor",
    age: 29,
    nationality: "US",
  },
  {
    id: 7,
    name: "Emily White",
    username: "emilyw",
    age: 26,
    nationality: "UK",
  },
  {
    id: 8,
    name: "Daniel Wilson",
    username: "danielw",
    age: 31,
    nationality: "CA",
  },
  {
    id: 9,
    name: "Linda Turner",
    username: "lindat",
    age: 33,
    nationality: "AU",
  },
  {
    id: 10,
    name: "Sam Adams",
    username: "samadams",
    age: 28,
    nationality: "US",
  },
  {
    id: 11,
    name: "Grace Parker",
    username: "gracep",
    age: 29,
    nationality: "UK",
  },
  {
    id: 12,
    name: "Tom Smith",
    username: "tomsmith",
    age: 35,
    nationality: "CA",
  },
  {
    id: 13,
    name: "Oliver Johnson",
    username: "oliverj",
    age: 30,
    nationality: "AU",
  },
  {
    id: 14,
    name: "Sophia Brown",
    username: "sophiab",
    age: 26,
    nationality: "NZ",
  },
  {
    id: 15,
    name: "Noah Lee",
    username: "noahl",
    age: 31,
    nationality: "US",
  },
  {
    id: 16,
    name: "Ava Taylor",
    username: "avat",
    age: 27,
    nationality: "UK",
  },
  {
    id: 17,
    name: "Mason White",
    username: "masonw",
    age: 32,
    nationality: "CA",
  },
  {
    id: 18,
    name: "Olivia Wilson",
    username: "oliviaw",
    age: 28,
    nationality: "AU",
  },
  {
    id: 19,
    name: "Liam Turner",
    username: "liamt",
    age: 29,
    nationality: "US",
  },
  {
    id: 20,
    name: "Aria Adams",
    username: "ariaa",
    age: 25,
    nationality: "UK",
  },
];

const Movies = [
  {
    id: 1,
    name: "The Matrix",
    yearOfPublication: 1999,
    isInTheaters: false,
  },
  {
    id: 2,
    name: "Inception",
    yearOfPublication: 2010,
    isInTheaters: false,
  },
  {
    id: 3,
    name: "Jurassic Park",
    yearOfPublication: 1993,
    isInTheaters: false,
  },
  {
    id: 4,
    name: "Avatar",
    yearOfPublication: 2009,
    isInTheaters: false,
  },
  {
    id: 5,
    name: "Titanic",
    yearOfPublication: 1997,
    isInTheaters: false,
  },
  {
    id: 6,
    name: "The Dark Knight",
    yearOfPublication: 2008,
    isInTheaters: false,
  },
  {
    id: 7,
    name: "Gladiator",
    yearOfPublication: 2000,
    isInTheaters: false,
  },
  {
    id: 8,
    name: "The Shawshank Redemption",
    yearOfPublication: 1994,
    isInTheaters: false,
  },
  {
    id: 9,
    name: "Forrest Gump",
    yearOfPublication: 1994,
    isInTheaters: false,
  },
  {
    id: 10,
    name: "Pulp Fiction",
    yearOfPublication: 1994,
    isInTheaters: false,
  },
];

module.exports = { UserList, Movies };
